### ISSUE TITLE
No booking/app/routes file in application

### ISSUE THREAD

**Issue by colintsteele** [revel/samples#11]
I'm not really sure how this application is supposed to run when the import:
 `github.com/reve/samples/booking/app/routes` does not exist.  I've attempted to point it at the `config/routes` file, but since that's not a .go file, it obviously won't work.  What is an `app/routes` file in revel supposed to look like?  Is it a simple map, or is it more complex?

**Comment by notzippy** [comment]
That routes files is auto created based on the config/routes file. If it did not get created, perhaps the directory is read only ?

**Comment by brendensoares** [comment]
[Default `conf/routes`](https://github.com/revel/revel/blob/master/skeleton/conf/routes) and [the manual section for URL Routing](http://revel.github.io/manual/routing.html)

Closing unless there is an actionable issue. Thanks!
