### ISSUE TITLE
Chat Error websocket

### ISSUE THREAD

**Issue by jniltinho** [revel/samples#4]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x4a5375]

goroutine 65 [running]:
code.google.com/p/go.net/websocket.Codec.Receive(0x9b6548, 0x9b6550, 0xc208082090, 0x7558e0, 0xc20818c2d0, 0x0, 0x0)
	/home/nilton/GO/src/code.google.com/p/go.net/websocket/websocket.go:314 +0x185
chat/app/controllers.func·001()
	/home/nilton/GO/src/chat/app/controllers/websocket.go:39 +0x92
created by chat/app/controllers.WebSocket.RoomSocket
	/home/nilton/GO/src/chat/app/controllers/websocket.go:46 +0x3ea

goroutine 1 [IO wait]:
net.(*pollDesc).Wait(0xc2080de060, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080de060, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc2080de000, 0x0, 0x7fc700e00db0, 0xc20818c010)
	/usr/local/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc20802c060, 0xc20813db68, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc20802c060, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:244 +0x4c
net/http.(*Server).Serve(0xc208064300, 0x7fc700e02b18, 0xc20802c060, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1728 +0x92
github.com/revel/revel.Run(0xa9da)
	/home/nilton/GO/src/github.com/revel/revel/server.go:129 +0xb01
main.main()
	/home/nilton/GO/src/chat/app/tmp/main.go:229 +0x2ec7

goroutine 5 [select]:
chat/app/chatroom.chatroom()
	/home/nilton/GO/src/chat/app/chatroom/chatroom.go:66 +0x678
created by chat/app/chatroom.init·1
	/home/nilton/GO/src/chat/app/chatroom/chatroom.go:97 +0x25

goroutine 33 [syscall]:
syscall.Syscall6(0xe8, 0x9, 0xc208165cb4, 0x7, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/asm_linux_amd64.s:46 +0x5
syscall.EpollWait(0x9, 0xc208165cb4, 0x7, 0x7, 0xffffffffffffffff, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:376 +0x93
gopkg.in/fsnotify%2ev1.(*fdPoller).wait(0xc208118660, 0x0, 0x0, 0x0)
	/home/nilton/GO/src/gopkg.in/fsnotify.v1/inotify_poller.go:85 +0xc7
gopkg.in/fsnotify%2ev1.(*Watcher).readEvents(0xc208111a90)
	/home/nilton/GO/src/gopkg.in/fsnotify.v1/inotify.go:179 +0x16f
created by gopkg.in/fsnotify%2ev1.NewWatcher
	/home/nilton/GO/src/gopkg.in/fsnotify.v1/inotify.go:58 +0x32b

goroutine 36 [IO wait]:
net.(*pollDesc).Wait(0xc2080de1b0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080de1b0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2080de150, 0xc20800f000, 0x1000, 0x1000, 0x0, 0x7fc700e00db0, 0xc20818cde8)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20802c100, 0xc20800f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
net/http.(*liveSwitchReader).Read(0xc2080664a8, 0xc20800f000, 0x1000, 0x1000, 0x742, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:214 +0xab
io.(*LimitedReader).Read(0xc208118160, 0xc20800f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:408 +0xce
bufio.(*Reader).fill(0xc208064960)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).ReadSlice(0xc208064960, 0xc2080b3a0a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:295 +0x257
bufio.(*Reader).ReadLine(0xc208064960, 0x0, 0x0, 0x0, 0xc2080b8500, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:324 +0x62
net/textproto.(*Reader).readLineSlice(0xc208120b70, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/textproto/reader.go:55 +0x9e
net/textproto.(*Reader).ReadLine(0xc208120b70, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/textproto/reader.go:36 +0x4f
net/http.ReadRequest(0xc208064960, 0xc20818e750, 0x0, 0x0)
	/usr/local/go/src/net/http/request.go:598 +0xcb
net/http.(*conn).readRequest(0xc208066460, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:586 +0x26f
net/http.(*conn).serve(0xc208066460)
	/usr/local/go/src/net/http/server.go:1162 +0x69e
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1751 +0x35e

goroutine 64 [runnable]:
chat/app/controllers.WebSocket.RoomSocket(0xc208072840, 0xc20817a0b0, 0x6, 0xc208082090, 0x0, 0x0)
	/home/nilton/GO/src/chat/app/controllers/websocket.go:50 +0x624
chat/app/controllers.(*WebSocket).RoomSocket(0xc20802c080, 0xc20817a0b0, 0x6, 0xc208082090, 0x0, 0x0)
	<autogenerated>:145 +0xcd
reflect.Value.call(0x89c900, 0xc20802c080, 0x2113, 0x8bad90, 0x4, 0xc20817a420, 0x2, 0x2, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:419 +0x10e5
reflect.Value.Call(0x89c900, 0xc20802c080, 0x2113, 0xc20817a420, 0x2, 0x2, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:296 +0xbc
github.com/revel/revel.ActionInvoker(0xc208072840, 0xc208065af8, 0x0, 0x0)
	/home/nilton/GO/src/github.com/revel/revel/invoker.go:36 +0x594
github.com/revel/revel.CompressFilter(0xc208072840, 0xc208065af8, 0x1, 0x1)
	/home/nilton/GO/src/github.com/revel/revel/compress.go:47 +0xa2
github.com/revel/revel.InterceptorFilter(0xc208072840, 0xc208065af0, 0x2, 0x2)
	/home/nilton/GO/src/github.com/revel/revel/intercept.go:103 +0x114
github.com/revel/revel.I18nFilter(0xc208072840, 0xc208065ae8, 0x3, 0x3)
	/home/nilton/GO/src/github.com/revel/revel/i18n.go:155 +0x2d7
github.com/revel/revel.ValidationFilter(0xc208072840, 0xc208065ae0, 0x4, 0x4)
	/home/nilton/GO/src/github.com/revel/revel/validation.go:191 +0x1e4
github.com/revel/revel.FlashFilter(0xc208072840, 0xc208065ad8, 0x5, 0x5)
	/home/nilton/GO/src/github.com/revel/revel/flash.go:46 +0x17c
github.com/revel/revel.SessionFilter(0xc208072840, 0xc208065ad0, 0x6, 0x6)
	/home/nilton/GO/src/github.com/revel/revel/session.go:149 +0x148
github.com/revel/revel.ParamsFilter(0xc208072840, 0xc208065ac8, 0x7, 0x7)
	/home/nilton/GO/src/github.com/revel/revel/params.go:133 +0xd9
github.com/revel/revel.FilterConfiguringFilter(0xc208072840, 0xc208065ac0, 0x8, 0x8)
	/home/nilton/GO/src/github.com/revel/revel/filterconfig.go:208 +0x212
github.com/revel/revel.RouterFilter(0xc208072840, 0xc208065ab8, 0x9, 0x9)
	/home/nilton/GO/src/github.com/revel/revel/router.go:474 +0x65c
github.com/revel/revel.PanicFilter(0xc208072840, 0xc208065ab0, 0xa, 0xa)
	/home/nilton/GO/src/github.com/revel/revel/panic.go:15 +0xb6
github.com/revel/revel.func·031(0xc208072840, 0xc208065aa8, 0xb, 0xb)
	/home/nilton/GO/src/github.com/revel/revel/watcher.go:232 +0x16e
github.com/revel/revel.handleInternal(0x7fc700e03ce0, 0xc208180000, 0xc20818e0d0, 0xc208082000)
	/home/nilton/GO/src/github.com/revel/revel/server.go:50 +0x3ee
github.com/revel/revel.func·046(0xc208082000)
	/home/nilton/GO/src/github.com/revel/revel/server.go:35 +0xf1
golang.org/x/net/websocket.Server.serveWebSocket(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x9b6a78, ...)
	/home/nilton/GO/src/golang.org/x/net/websocket/server.go:90 +0x292
golang.org/x/net/websocket.Handler.ServeHTTP(0xc208198180, 0x7fc700e03ce0, 0xc208180000, 0xc20818e0d0)
	/home/nilton/GO/src/golang.org/x/net/websocket/server.go:113 +0x8a
github.com/revel/revel.handle(0x7fc700e03ce0, 0xc208180000, 0xc20818e0d0)
	/home/nilton/GO/src/github.com/revel/revel/server.go:36 +0x31e
net/http.HandlerFunc.ServeHTTP(0x9b6a18, 0x7fc700e03ce0, 0xc208180000, 0xc20818e0d0)
	/usr/local/go/src/net/http/server.go:1265 +0x41
net/http.serverHandler.ServeHTTP(0xc208064300, 0x7fc700e03ce0, 0xc208180000, 0xc20818e0d0)
	/usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc208180f00)
	/usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1751 +0x35e

**Comment by jniltinho** [comment]
Fix, 
go get github.com/revel/samples
cd github.com/revel/samples/chat
revel run github.com/revel/samples/chat

No bug, sorry

**Comment by brendensoares** [comment]
:+1:
