### ISSUE TITLE
README wrong guide

### ISSUE THREAD

**Issue by teddy-hoo** [revel/samples#6]
it seems that the command "go get github.com/revel/samples/..." should be used instead of  command "go get github.com/revel/samples" to get all the samples.

**Comment by DavidHunter** [comment]
"go get github.com/revel/samples/..." that command gives errors

**Comment by DavidHunter** [comment]
"git clone https://github.com/revel/samples.git $GOPATH/src/github.com/revel/samples" this works

**Comment by brendensoares** [comment]
```
$ go get github.com/revel/samples
package github.com/revel/samples
	imports github.com/revel/samples
	imports github.com/revel/samples: no buildable Go source files in /Users/brenden/.gvm/pkgsets/go1.4/global/src/github.com/revel/samples
```

We could add a `main.go` to fix this issue or you can do as @DavidHunter mentions OR you could `go get` each sample on its own.

If you have more questions that don't involve bugs in Revel's source code, try our mailing list of StackOverflow.com.

Thanks!

**Comment by brendensoares** [comment]
@DavidHunter explained in IRC that we should probably change the readme in this repo to avoid that error, but `go get` still checks out the entire samples repo even though it shows that code.

**Comment by brendensoares** [comment]
Fixed :)

**Comment by teddy-hoo** [comment]
^_^
