### ISSUE TITLE
No routes found

### ISSUE THREAD

**Issue by ngavrish** [revel/samples#8]
$ go get github.com/revel/samples/...
package github.com/revel/samples/booking/app/controllers
	imports github.com/revel/samples/booking/app/routes: cannot find package "github.com/revel/samples/booking/app/routes" in any of:
	/usr/local/go/src/github.com/revel/samples/booking/app/routes (from $GOROOT)
	/Users/802619/soft/golang/src/github.com/revel/samples/booking/app/routes (from $GOPATH)
package github.com/revel/samples/chat/app/controllers
	imports github.com/revel/samples/chat/app/routes: cannot find package "github.com/revel/samples/chat/app/routes" in any of:
	/usr/local/go/src/github.com/revel/samples/chat/app/routes (from $GOROOT)
	/Users/802619/soft/golang/src/github.com/revel/samples/chat/app/routes (from $GOPATH)
go: missing Mercurial command. See https://golang.org/s/gogetcmd
package github.com/revel/samples/facebook-oauth2/app/controllers
	imports code.google.com/p/goauth2/oauth: exec: "hg": executable file not found in $PATH
package github.com/revel/samples/upload/app/controllers
	imports github.com/revel/samples/upload/app/routes: cannot find package "github.com/revel/samples/upload/app/routes" in any of:
	/usr/local/go/src/github.com/revel/samples/upload/app/routes (from $GOROOT)
	/Users/802619/soft/golang/src/github.com/revel/samples/upload/app/routes (from $GOPATH)

**Comment by pedromorgan** [comment]
umm..
```go: missing Mercurial command```
so maybe `apt-get install mercurial` solves that one..

I'll run the samples later, when i get home

**Comment by ngavrish** [comment]
Well, actually you don't have routes indeed if you look at github web UI for your repo

**Comment by pedromorgan** [comment]
Are you actually tapping in
```go get github.com/revel/samples```
?

**Comment by ngavrish** [comment]
If I type this, I'll get that:

$ go get github.com/revel/samples
can't load package: package github.com/revel/samples: no buildable Go source files in /Users/802619/soft/golang/src/github.com/revel/samples

**Comment by ngavrish** [comment]
I am on mac os

**Comment by brendensoares** [comment]
I agree with @pedromorgan, you need to install `hg`. If you solved it, please share the solution.
